services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ${DB_NAME}
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
      MSSQL_PID: ${MSSQL_PID}
    ports:
      - "1433:1433"
    volumes:
      - filmnet_db_data:/var/opt/mssql
        
volumes:
  filmnet_db_data: